### PR TITLE
Doesn't work in versions higher than 52

### PR DESCRIPTION
**Pull request by mileyvirus**
Sketch team deprecated shapeWithPath. I made a pull request to fix it and now works on Sketch 52.5.

This was the error:
`TypeError: MSShapeGroup.shapeWithPath is not a function.`

### CODE REVIEW

**Review by lewishowles — APPROVED** [review]
Thank you for the pull request.

**Review by lewishowles — APPROVED** [review]

**Comment by mileyvirus** [comment]
Thanks for your work! 👊
